version: '3.5'

services:
  keycloak:
    build: ./keycloak/.
    container_name: uwithme-keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8080:8080"

  db:
    image: postgres:14.2-bullseye
    container_name: uwithme-postgres
    restart: always
    volumes:
      - ./postgres-config:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
#     - "host-port:container-port"
      - "5432:5432"