version: '3.5'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.5
    container_name: uwithme-keycloak
    restart: always
    volumes:
      - ./keycloak-config:/opt/keycloak/data/import
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev --import-realm
    ports:
      - "8080:8080"

  db:
    image: postgres:15.2
    container_name: uwithme-postgres
    restart: always
    volumes:
      - ./postgres-config:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
#     - "host-port:container-port"
      - "5432:5432"