#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER "${KEYCLOAK_DB_USER}" WITH PASSWORD '${KEYCLOAK_DB_PASSWORD}';
    ALTER DATABASE keycloak OWNER TO "${KEYCLOAK_DB_USER}";
    GRANT ALL PRIVILEGES ON DATABASE keycloak TO "${KEYCLOAK_DB_USER}";

    CREATE USER "${U_WITH_ME_DB_USER}" WITH PASSWORD '${U_WITH_ME_DB_PASSWORD}';
    ALTER DATABASE uwithme OWNER TO "${U_WITH_ME_DB_USER}";
    GRANT ALL PRIVILEGES ON DATABASE uwithme TO "${U_WITH_ME_DB_USER}";

    CREATE USER "${TEST_SYSTEM_DB_USER}" WITH PASSWORD '${TEST_SYSTEM_DB_PASSWORD}';
    ALTER DATABASE testsystem OWNER TO "${TEST_SYSTEM_DB_USER}";
    GRANT ALL PRIVILEGES ON DATABASE testsystem TO "${TEST_SYSTEM_DB_USER}";

    CREATE USER "${BOT_DB_USER}" WITH PASSWORD '${BOT_DB_PASSWORD}';
    ALTER DATABASE unibot OWNER TO "${BOT_DB_USER}";
    GRANT ALL PRIVILEGES ON DATABASE unibot TO "${BOT_DB_USER}";
EOSQL
